== Chromosomy
Każdy z chromosomów reprezentuje jedno możliwe rozwiązanie, a każdy z chromosomów składa się z ((allel))i (czasem zwanymi genami), które stanowią drobną część (na przykład bit, znak lub liczbę) będącą częścią tegoż rozwiązania  <<Kumar2010>>.

#TODO: TBD#

=== `GeneableChromosome` – implementacja
W naszym rozwiązaniu chromosom może implementować interfejs `IChromosome`, który przechowuje jedynie wartość dopasowania (`Fitness`). 
Jednak w celu uproszczenia implementacji, postępując zgodnie z zasadą DRY (z ang. _don't repeat yourself_ – nie powtarzaj siebie) wprowadzono interfejs `IGeneableChromosome`, który pozwala na dekompozycję każdego rozwiązania na drobne kawałki. 
Definicja tychże interfejsów prezentuje się następująco: 

#TODO: Dodać ilustrację chromosomu z różnymi genami#

[source,csharp]
.Interfejsy dla ((chromosom))ów
----
public interface IChromosome : IComparable
{
    double? Fitness { get; set; }
}
public interface IGenableChromosome<T> : IChromosome
{
    public IReadOnlyList<T> Genes { get; }
}
----
#TODO: TBD#

=== Funkcja dopasowania
Funkcja dopasowania jest inna dla każdego problemu i służy do oceny danego rozwiązania (chromosomu) footnote:[https://en.wikipedia.org/wiki/Fitness_function].
Najczęściej spotykanym traktowania dopasowania jest „im większe, tym lepsze”, aczkolwiek w naszym rozwiązaniu możliwe jest odwrócenie tej zasady, co pozwala na naturalne pisanie funkcji optymalizacyjnych.
Z takiej możliwości korzysta rozwiązanie problemu ((komiwojażer))a, gdzie wartość dopasowania jest równa długości ścieżki, jaką musi przebyć, a ta jest tym lepsza, im jest krótsza. 

Przykłady implementacji funkcji dopasowania zostaną przedstawione w następnych rozdziałach przy okazji omówienia poszczególnych problemów.