== Krzyżowanie
Krzyżowanie, czasem zwane również ((rekomobinowanie))m, to proces łączenia genów rodziców w taki sposób, aby uzyskać nowego potomka, reprezentujące nowe rozwiązanie <<Kumar2010>>. 

=== Krzyżowanie uporządkowane 
indexterm:[Krzyżowanie, Ordered]
indexterm:[Krzyżowanie, OX1]
Krzyżowanie uporządkowane jest w szczególności przydatne, gdy mamy do czynienia z chromosomami, których geny mogą pochodzić tylko ze ściśle określonej puli footnote:[https://www.tutorialspoint.com/genetic_algorithms/genetic_algorithms_crossover.htm]. 

#TODO Dodać przykład!#

[source,csharp]
.Implementacja OrderedCrossover
----
public class OrderedCrossover<T, E> : ICrossover<T> where T : IGenableChromosome<E>
{
    private static readonly Random _random = new();
    public double Begining { get; }
    public double End { get; }

    private readonly IGenableChromosomeFactory<T, E> _factory;

    public int RequiredNumberOfParents { get; } = 2;

    public IEnumerable<T> MakeChildren(IEnumerable<T> parentsRaw)
    {
        var parents = parentsRaw.ToList();
        if (parents.Count != RequiredNumberOfParents)
            throw new ArgumentException("The number of parents isn't sufficient", nameof(parentsRaw));
        if (parents[0].Genes.Count != parents[1].Genes.Count)
            throw new ArgumentException("Different size of genes is not supported here!");

        var maxCount = parents[0].Genes.Count;


        var begining = (int) (maxCount * Math.Min(Begining, End)); <1>
        var end = (int) (maxCount * Math.Max(Begining, End));

        var child1PrimeGenes = parents[0].Genes.Skip(begining).Take(end - begining).ToList(); <2>
        var child2PrimeGenes = parents[1].Genes.Skip(begining).Take(end - begining).ToList();

        var parent1FilteredGens = parents[0].Genes.Where(d => !child2PrimeGenes.Contains(d)).ToList(); <3>
        var parent2FilteredGens = parents[1].Genes.Where(d => !child1PrimeGenes.Contains(d)).ToList();

        var child1Genes = <4>
            parent2FilteredGens.Take(begining)
                                .Concat(child1PrimeGenes)
                                .Concat(parent2FilteredGens.Skip(begining)
                                                            .Take(maxCount - (begining + child1PrimeGenes.Count)));

        var child2Genes =
            parent1FilteredGens.Take(begining)
                                .Concat(child2PrimeGenes)
                                .Concat(parent1FilteredGens.Skip(begining)
                                                            .Take(maxCount - (begining + child2PrimeGenes.Count)));

        yield return _factory.FromGenes(child1Genes.ToList());
        yield return _factory.FromGenes(child2Genes.ToList());
    }
}
----

<1> Na początku określamy miejsca zwrotne, w których będziemy zmieniać źródło genów. 
Zmienne `Begining` i `End` (proszę zwrócić uwagę na wielkie litery) określają procentowo miejsce zwrotne. 
Miejsce określone bezwzględnie przechowywane jest w zmiennych o tych samych nazwach, lecz z małych liter.
<2> W tym miejscu pobierane są geny z rodziców, które zostaną u potomków,
<3> W tym miejscu ze względu optymalizacyjnych są określane geny, które nie zostały jeszcze wykorzystane w kroku <2>.
<4> W tym miejscu dochodzi do połączenia genów jednego rodzica (z kroku <2>) z pozostałymi genami rodzica drugiego (z kroku <3>).

=== Cyclic Ordered Chrossover
#TODO: Znaleźć bibliografię#
Uporządkowane krzyżowanie cykliczne jest oparte o wybrany (lub losowy) okres, który działa według następującego sposobu:

. Podziel chromosom pierwszego rodzica na kawałki o wybranej długości (okres),
. Odrzuć co drugi kawałek,
. W puste miejsca wstaw pozostałe geny drugiego rodzica.
. Wykonaj to samo dla drugiego rodzica. 

indexterm:[Krzyżowanie, uniform]
Działanie to przypomina krzyżowanie jednolite (uniform crossover) z tą różnicą, że zapewnione jest, że wszystkie geny, które występują u obojga rodziców, wystąpią również u potomków.

#TODO: Dodać ilustrację#

[source,csharp]
.Implementacja CyclicOrderedCrossover
----
public class CyclicOrderedCrossover<T, E> : ICrossover<T> where T : IGenableChromosome<E>
{
    private static readonly Random _random = new();
    public int? Length { get; }
    private readonly IGenableChromosomeFactory<T, E> _factory;

    public int RequiredNumberOfParents { get; } = 2;

    public IEnumerable<T> MakeChildren(IEnumerable<T> parentsRaw)
    {
        var parents = parentsRaw.ToList();
        if (parents.Count != RequiredNumberOfParents)
            throw new ArgumentException("The number of parents isn't sufficient", nameof(parentsRaw));
        if (parents[0].Genes.Count != parents[1].Genes.Count)
            throw new ArgumentException("Different size of genes is not supported here!");

        var maxCount = parents[0].Genes.Count;
        var cycleLength = Length ?? _random.Next(maxCount);

        if (cycleLength >= maxCount)
            throw new InvalidOperationException("Length of cycle is lower than length of chromosome!");

        int i = 0;

        {
            i = 0;
            var child1Prime = parents[0].Genes.GroupBy(_ => i++ / cycleLength).Where(d => d.Key % 2 == 0).ToList();
            i = 0;
            var child1Supplement = parents[1].Genes.Where(d => !child1Prime.Any(e => e.Contains(d)))
                                             .GroupBy(_ => i++ / cycleLength).ToList();
            var readyKid1 = new List<E>();
            i = 0;
            foreach (var kidPart in child1Prime)
            {
                readyKid1.AddRange(kidPart);
                if (i >= child1Supplement.Count) break;
                readyKid1.AddRange(child1Supplement.ElementAt(i++));
            }

            yield return _factory.FromGenes(readyKid1);
        }
        {
            i = 0;
            var child2Prime = parents[1].Genes.GroupBy(_ => i++ / cycleLength).Where(d => d.Key % 2 == 0).ToList();


            i = 0;
            var child2Supplement = parents[1].Genes.Where(d => !child2Prime.Any(e => e.Contains(d)))
                                             .GroupBy(_ => i++ / cycleLength).ToList();
            var readyKid2 = new List<E>();
            i = 0;
            foreach (var kidPart in child2Prime)
            {
                readyKid2.AddRange(kidPart);
                if (i >= child2Supplement.Count) break;
                readyKid2.AddRange(child2Supplement.ElementAt(i++));
            }

            yield return _factory.FromGenes(readyKid2);
        }
    }
}
----

=== Jedno- i wielo- punktowe krzyżowanie
indexterm:[Krzyżowanie, singlepoint]
indexterm:[Krzyżowanie, multipoint]
Krzyżowania te opierają się na tym, że budowanie chromosomu dziecka następuje raz z genów rodzica pierwszego, a raz z rodzica drugiego.
I tak w przypadku krzyżowania jedno punktowego wybieramy jedno miejsce (lub losujemy), a w przypadku krzyżowania wielopunktowego tych miejsc jest wiele footnote:[https://en.wikipedia.org/wiki/Crossover_(genetic_algorithm)].
Co ciekawe, krzyżowanie jednopunktowe można rozpatrywać jako szczególny przypadek krzyżowania wielopunktowego – tę możliwość wykorzystano również w implementacji. 
Dlatego też, poniższy kod reprezentuje tylko krzyżowanie wielopunktowe.

#TODO: Dodać ilustrację#

[source,csharp]
.Implementacja MultipointCrossover
----
public class MultiPointCrossover<T, E> : ICrossover<T> where T : IGenableChromosome<E>
{
    private readonly int _amountOfPoints;
    private readonly IGenableChromosomeFactory<T, E> _factory;
    private List<int> _splitPoints;
    public int RequiredNumberOfParents => 2;

    public IEnumerable<T> MakeChildren(IEnumerable<T> parents)
    {
        var list = parents.ToList();
        if (list.Count != RequiredNumberOfParents)
            throw new ArgumentException("The number of parents isn't sufficient", nameof(parents));
        if (list[0].Genes.Count != list[1].Genes.Count)
            throw new ArgumentException("Different size of genes is not supported here!");

        var maxCount = list[0].Genes.Count;
        var childGenes1 = new List<E>();
        var childGenes2 = new List<E>();
        var random = new Random();

        if (_splitPoints == null || _splitPoints.Count == 0)
        {
            _splitPoints = new List<int>(_amountOfPoints);
            for (int j = 0; j < _amountOfPoints; ++j) _splitPoints.Add(random.Next(maxCount - 1));
            _splitPoints.Sort();
        }

        for (int i = 0; i < maxCount; ++i)
        {
            int next = _splitPoints.Count(d => d >= i) % 2;
            childGenes1.Add(next == 0 ? list[0].Genes[i] : list[1].Genes[i]);
            childGenes2.Add(next == 1 ? list[0].Genes[i] : list[1].Genes[i]);
        }

        yield return _factory.FromGenes(childGenes1);
        yield return _factory.FromGenes(childGenes2);
    }
}
----

=== Uniform Crossover
#TODO: Znaleźć bibliografię#
indexterm:[Krzyżowanie, Uniform]
Krzyżowanie jednorodne polega na równomiernym pobraniu materiału genetycznego od każdego z rodziców i jego równomierne rozłożenie.

#TODO: Dodać przykład#

[source,csharp]
.Implementacja UniformCrossover
----
public class UniformCrossover<T, E> : ICrossover<T> where T : IGenableChromosome<E>
    {
        private readonly IGenableChromosomeFactory<T, E> _factory;
        public int RequiredNumberOfParents => 2;

        public IEnumerable<T> MakeChildren(IEnumerable<T> parents)
        {
            var list = parents.Take(RequiredNumberOfParents).ToList();
            if (list.Count != RequiredNumberOfParents)
                throw new ArgumentException("The number of parents isn't sufficient", nameof(parents));
            if (list[0].Genes.Count != list[1].Genes.Count)
                throw new ArgumentException("Different size of genes is not supported here!");

            var maxCount = list[0].Genes.Count;
            var childGenes1 = new List<E>();
            var childGenes2 = new List<E>();
            var random = new Random();
            for (int i = 0; i < maxCount; ++i)
            {
                int next = random.Next(1); <1>
                childGenes1.Add(next == 0 ? list[0].Genes[i] : list[1].Genes[i]);
                childGenes2.Add(next == 1 ? list[0].Genes[i] : list[1].Genes[i]);
            }

            yield return _factory.FromGenes(childGenes1);
            yield return _factory.FromGenes(childGenes2);
        }
    }
----

<1> W tym miejscu dokonujemy decyzji, za pomocą losowania, czy dany gen ma pochodzić od rodzica pierwszego, czy od rodzica drugiego.
