== Algorytm optymalizacji rojem cząstek (PSO)
Algorytm PSO (z ang. _particle swarm optimization_) należy do grupy najpopularniejszych algorytmów opartych o zaobserwowane zachowania natury. 
Wśród nich znajdują się takie algorytmy jak: mrówkowy, pszczeli i ławicy ryb.
Ich popularność wynika z prostoty przystosowania do wielu problemów <<wiatrak2015>>. 

Algorytm optymalizacji rojem cząstek został zaprezentowany przez Kennediego i Eberharta w 1995 roku. 
Jest on oparty na sposobie przemieszania się stada ptaków, gdzie każdy z nich porusza się z prędkością zależną od doświadczeń własnych i grupy, do której należy <<wiatrak2015>>.

Algorytm ten w implementacji jest podobny do algorytmu genetycznego, ponieważ składa się on z następujących kroków:

. Wylosowanie grupy początkowej (inicjalizacja populacji),
. Określenie dopasowania, czyli położenia cząstki – im niżej ona leży, tym lepiej (funkcja dopasowania),
. Przesunięcia cząstek w pożądanym kierunku (krzyżowanie i utworzenie nowej populacji).

W niniejszej pracy implementacji algorytmu optymalizacji rojem cząstek dokonano w języku JavaScript celem sprawdzenia, jak inaczej wprowadza się w życie elementy sztucznej inteligencji w tym języku.
Dodatkowo wykorzystanie technologii webowej pozwala na zdecydowanie łatwiejsze realizowanie wizualizacji niż technologie typowo desktopowe czy serwerowe.

[source,javascript]
.Przedstawienie głownego założenia PSO w PHP.
----
let dataPoints = [];
let bestGlobal = [];
let bestGlobalFitness = [];

let particles = [];
let best_globals = [];
let c_1;
let c_2;
let r_1;
let r_2;
let t;
let n;
let position_min;
let position_max;
let inertia_min;
let inertia_max;

initialization();
pso();
chartRenderer();
chartPresentation();
----

Funkcja inicjujaca ustawia parametry początkowe takie jak: liczba iteracji, ilość elementów w roju.
Należy ją również zmodyfikować w przypadku zmiany zakresu dla wartości X i Y. 
Dodatkowo wylosowane zostają pozycje startowego dla każdego z elementów.

[source,javascript]
.Funkcja inicjująca PSO
----
function initialization()
{
    t = 50;
    n = 25;
    inertia_min = 0.4;
    inertia_max = 0.9;
    c_1 = 2;
    c_2 = 2;
    position_min = -4.5;
    position_max = 4.5;
    r_1 = rand(0, 1); 
    r_2 = rand(0, 1); 

    for (let i = 0; i < n; i++)
    {
        particles[i] = [];
        particles[i]['x'] = [];
        particles[i]['x']['position'] = 0;
        particles[i]['x']['best_local_position'] = 0;
        particles[i]['x']['velocity'] = 0;
        particles[i]['y'] = [];
        particles[i]['y']['position'] = 0;
        particles[i]['y']['best_local_position'] = 0;
        particles[i]['y']['velocity'] = 0;
        particles[i]['best_local_fitness'] = 0;
    }

    for (let i = 0; i < n; i++)
    {
        particles[i]['x']['position'] = rand(position_min, position_max);
        particles[i]['x']['best_local_position'] = particles[i]['x']['position'];
        particles[i]['x']['velocity'] = 0;

        particles[i]['y']['position'] = rand(position_min, position_max);
        particles[i]['y']['best_local_position'] = particles[i]['y']['position'];
        particles[i]['y']['velocity'] = 0;

        particles[i]['best_local_fitness'] = fitness(particles[i]['x']['position'], particles[i]['y']['position']);
    }
            
    let best_global = Infinity;
    let best_global_id = 0;
    for (let i = 0; i < n; i++)
    {
        if (particles[i]['best_local_fitness'] < best_global) 
        {
            best_global = particles[i]['best_local_fitness'];
            best_global_id = i;
        }
    }
        
    best_globals['x'] = particles[best_global_id]['x']['position'];
    best_globals['y'] = particles[best_global_id]['y']['position'];
    best_globals['fitness'] = fitness(best_globals['x'], best_globals['y']);
}
----

Najważniejsza funkcja, która odpowiada za bezpośrednią implementację algorytmu optymalizacji rojem cząstek. 
Wyznacza najlepsze dopasowanie lokalne każdej z cząstek, wyznacza również najlepsze dopasowanie globalne i aktualizuje wektor prędkości każdej z cząstek.
Wszystkie wartości są zapisywane do tablicy, co umożliwia wykonanie wizualizacji.

[source,javascript]
.Funkcja wykonująca algorytm PSO
----
function pso()
{
    for (let i = 0; i < t; i++)
    {
        for (let j = 0; j < n; j++)
        {
            best_local_fitness = fitness(particles[j]['x']['position'], particles[j]['y']['position']);
            if (particles[j]['best_local_fitness'] > best_local_fitness) 
            {
                particles[j]['best_local_fitness'] = best_local_fitness;
                particles[j]['x']['best_local_position'] = particles[j]['x']['position'];
                particles[j]['y']['best_local_position'] = particles[j]['y']['position'];
            }
        }
  
        for (let j = 0; j < n; j++)
        {
            if (particles[j]['best_local_fitness'] < best_globals['fitness'])
            {
                best_globals['fitness'] = particles[j]['best_local_fitness'];
                best_globals['x'] = particles[j]['x']['position'];
                best_globals['y'] = particles[j]['y']['position'];
            }
        }

        dataPoints[i] = [];
        for (let j = 0; j < n; j++)
        {
            particles[j]['x']['velocity'] = inertia(i) *
                particles[j]['x']['velocity'] +
                ( c_1 * rand(0, 1) ) *
                ( particles[j]['x']['best_local_position'] - particles[j]['x']['position'] ) +
                ( c_2 * rand(0, 1) ) *
                ( best_globals['x'] - particles[j]['x']['position']);

            particles[j]['y']['velocity'] = inertia(i) *
                particles[j]['y']['velocity'] +
                ( c_1 * rand(0, 1) ) *
                ( particles[j]['y']['best_local_position'] - particles[j]['y']['position'] ) +
                ( c_2 * rand(0, 1) ) *
                ( best_globals['y'] - particles[j]['y']['position']);

            particles[j]['x']['position'] = particles[j]['x']['position'] + particles[j]['x']['velocity'];
            particles[j]['y']['position'] = particles[j]['y']['position'] + particles[j]['y']['velocity'];
                    
            dataPoints[i].push({
                'x': particles[j]['x']['position'],
                'y': particles[j]['y']['position'],
            }); 
        }
                
        bestGlobal[i] = [];
        bestGlobal[i].push({
            'x': best_globals['x'],
            'y': best_globals['y'],
        });
        bestGlobalFitness[i] = best_globals['fitness'];
    }
}

function fitness(x, y) 
{
    // Bale'a || od -4,5 do 4,5
    return  -(Math.pow(1.5 - x + x * y, 2) + Math.pow(2.25 - x + x * y * y, 2) + Math.pow(2.625 - x + x * y * y * y, 2));
}

function rand(from = 0, to = 1)
{
    return Math.round(((Math.random() * (to - from) + from) + Number.EPSILON) * 100) / 100;
}

function inertia(i)
{
    return 0.1;
 }
----

Funkcja generująca wizualizację działania algorytmu PSO.

[source,javascript]
.Funkcja odpowiedzialna za wyrysowanie wykresu do wizualizacji
----
function chartRenderer()
{
    let chart = new CanvasJS.Chart("chartContainer", {
        title:{
            text: 'PSO'             
        },
        axisY:{
            minimum: position_min * 10,
            maximum: position_max * 10,
        },
        axisX:{
            minimum: position_min * 10,
            maximum: position_max * 10,
        },
        data: [              
            {
                showInLegend: true, 
                name: "Position",
                legendText: "Position",
                lineColor: "blue",
                type: "scatter",
                markerSize: 5,
                dataPoints: dataPoints,
            },
            {
                showInLegend: true, 
                name: "Best global position",
                legendText: "Best global position",
                lineColor: "red",
                type: "scatter",
                markerSize: 10,
                dataPoints: bestGlobal,
            }
        ]
    });
    chart.render();
}

function chartPresentation()
{
    for (let i = 1; i < t; i++) {
        setTimeout(function timer() {
            chart.options.data[0].dataPoints = dataPoints[i];
            chart.options.data[1].dataPoints = bestGlobal[i];
            chart.render();
        }, i * 200);
    }
}
----