= Problemy dla algorytmów genetycznych i implementacja
Algorytmy genetyczne są uważane za proces wyszukiwania dokładnego lub zbliżonego rozwiązania problemu. 
W związku z tym najlepiej radzą sobie w funkcjach optymalizacyjnych, gdzie znana jest funkcja dopasowania <<Kumar2010>>. 

Wszystkie operatory oraz elementy problemów zostały zaimplementowane w języku C# na platformie .Net Core 3.1.
Architektura algorytmu została oparta na rozwiązaniu znanym z biblioteki ((GeneticSharep)) footnote:[https://github.com/giacomelli/GeneticSharp].
Różnica między tą popularną otwartoźródłową biblioteką a naszą implementacją polega głównie na tym, że postawiliśmy na silne typowanie, to znaczy, że wszystkie elementy algorytmu są świadome typu chromosomu, fabryki i funkcji dopasowanie.
Takie podejście pozwala na większą świadomość programisty na temat typów, z którymi pracuje i zwalnia z potrzeby ciągłego rzutowania obiektów (zmiany typu z jednego na drugi).
Dodatkowo została wydzielona odpowiedzialność fabryki – w źródłowej bibliotece za produkcje kolejnych chromosomów odpowiadała sama klasa chromosomu, co wydaje nam się naruszeniem zasady pojedynczej odpowiedzialności (z ang. _single responsibility principle_).

include::problem_plecakowy.adoc[]

include::problem_komiwojazera.adoc[]

include::optymalizacja_funkcji.adoc[]

