== Problem plecakowy
W trakcie realizacji pracy spróbowaliśmy znaleźć najlepsze rozwiązanie dla problemu plecakowego z użyciem algorytmu genetycznego naszej implementacji.

Problem plecakowy dyskretny, znany czasem jako problem złodzieja rabującego sklep, polega na tym, aby do plecaka o ograniczonej pojemności zapakować tylko taki zestaw przedmiotów, który pozwoli zabrać jak najwięcej pod względem wartości. 
Przy tym wszystkim nie można zabrać ze sobą połowy przedmiotu footnote:[https://pl.wikipedia.org/wiki/Problem_plecakowy].

Wszystkie przedstawione poniżej wyniki zostały oparte na zestawie danych dostępnym pod adresem http://artemisa.unicauca.edu.co/~johnyortega/instances_01_KP. 
Wybrany do badań zestaw posiada 200 elementów o różnej wadze i wartości, a maksymalna pojemność plecaka to 1008.
Najlepsza możliwa wartość to 1634. 

Problem ten w kwestii funkcji dopasowania jest dość podobny do problemu komiwojażera.
W obu przypadkach mamy do czynienia ze skończonym i jasno określonym zestawem genów (przedmiotów do zabrania). 
Różnica polega na tym, że w przypadku komiwojażera do wyliczenia funkcjo dopasowania bierze się wszystkie elementy, tak przy problemie plecakowym liczy się tylko tyle elementów, ile zmieści się do plecaka.

=== Implementacja

Funkcja dopasowania działa w taki sam sposób, jak zaprezentowane we wstępie do rozdziału.

[source,csharp]
.Funkcja obliczająca dopasowanie, czyli wartość wkładu plecaka
----
public class KnapsackFitness : IFitness<KnapsackProblemChromosome>
{
    public double Evaluate(KnapsackProblemChromosome chromosome)
    {
        var weight = 0.0;
        var profit = 0.0;

        foreach (var insert in chromosome.Genes) <1>
        {
            if (weight + insert.Weight < chromosome.MaxWeight) <2>
            {
                weight += insert.Weight;
                profit += insert.Profit;
            }
            else { break; }
        }

        chromosome.TotalWeight = weight;
        chromosome.TotalProfit = profit;

        return profit;
    }
}
----

<1> Dobieramy geny od początku,
<2> aż do momentu, kiedy ich łączna waga przekroczy pojemność plecaka.

#TODO: Dodać wyniki pomiarów#
