= Wrażenia z gry Sea of Solitude z 2019 roku studia Jo-Mei Games
Mikołaj Dalecki <mikolaj.dalecki@outlook.com>
:toc:

[.lead]
Dziś na temat specyficznej gry _Sea of Solitude_ (co można bezpośrednio przełożyć na _morze osamotnienia_, bądź _morze samotności_). 
Gra ta opowiada historię Kay i o jej walce z problemami w rodzinie (z bratem i rodzicami) oraz z chłopakiem. 

WARNING: Jedyne miejsce wolne od spojlerów to część „Krótka recenzja”, dalsza treść jest napisana w celu zachęcenia do dyskusji po ukończeniu gry.

== Krótka recenzja

Grę uruchomiłem w lutym 2021 roku na konsoli Xbox One X – była ona dostępna w ramach abonamentu EA Play (a ten w ramach Xbox Game Pass Ulimate). 
Gra charakteryzuje się  animowaną grafiką posiadającą wiele zaokrągleń i generalnie przyjemną dla oka (grafika kojarzy się z _Drake Hollow_). 
Muzyka jest, nawet całkiem niezła – potrafi dobrze wprowadzić w nastrój choć czase potrafi również zmylić. 

Sama fabuła porusza temat samotności i zmagań kilkunasto (?), dwudziestoletniej (?) bohaterki.
Prowadzi nas poprzez jej egoizm, poczucie winy i odrzucenie. 
W samej grze nie występuje praktycznie żadna przemoc, jest kilka drobnych elementów zręcznościowych i nie ma praktycznie niczego co mogłoby sprawić trudności. 

Jest to pierwsza gra w języku angielskim jaką zdecydowałem się przejść mimo mojej niechęci do obcowania z materiałami w językach obcych i nie żałuję – słownictwo wykorzystywane w tej produkcji jest proste a zarazem wystarczające aby przedstawić to co ważne. 
Niestety nic mi nie wiadomo na temat jakiegokolwiek spolszczenia choćby na PC.

== Ogólnie o grze 

Cóż, dziś będzie krótko, bo i sama gra nie jest za długa (tak z 5-10 godzin) ani nie ma się za bardzo o czym rozpisywać. 

Sama gra nie wywołała we mnie jakiś super emocji. 
Natomiast muszę przyznać, że sposób prowadzenia narracji jest ciekawy – pierwszy etap, dotyczący brata, zapadł mi w szczególności poprzez szkołę, a w szczególności przez ciemną „bibliotekę” gdzie musieliśmy unikać małych monstrów. 
W drugim etapie najbardziej spodobała mi się krótka przygoda na „rynku”, gdzie rodzice głównej bohaterki wybrali się na pierwszą randkę. 
Trzeci natomiast poprzez to że sami goniliśmy potwora, który na początku starał się nam przeszkodzić, i dlaczego musieliśmy go poświęcić? 

Sama rozgrywka nie jest trudna, znajdźki to „listy w butelce” oraz mewy. 
Niestety nie udało mi się znaleźć wszystkich, bo po chwili okazało się, że nie można cofnąć się do wcześniejszych lokacji tak po prostu a gra w żaden sposób o tym nie informuje za wczasu, co uważam za minus. 

== Podsumowanie

Ogólnie po grze nie mogę zrozumieć, dlaczego wybrano reprezentację takich a nie innych monstrów: brat – kruk, ojcec – kameleon, matka – ośmiornica, wilk – partner głównej bohaterki. 
Co ma znaczyć ten „rekin”, który urzędował w wodzie a już w ogóle te ręce które czasem wychodziły z zielonkawej wody? 
Kim była dziewczynka w złotym ubranku i dlaczego chciała nam przeszkodzić (wyjaśnienie, że to ona powinna była rozmawiać z Wilkiem nie jest wystarczające). 

Uważam, że w grę warto zagrać choćby dlatego że jest trochę inna niż inne i do tego nie za długa. Moja ocena to mocno 6.5/10.
