= Wykorzystanie Docker'a w celu zachowania czystości. Część 02 - Visual Studio Code
Mikołaj Dalecki <mikolaj.dalecki@outlook.com>
:toc:
:source-highlighter: pygments
:note-caption: Uwaga
:imagesdir: ./img

[.lead]
W niniejszym artykule przedstawiam mój sposób na pracę z Dockerem w taki sposób, aby zachować czystość komputera przy używaniu nowych technologii w celu nauki lub sporadycznym wykorzystaniu. 
Założenia, które sobie stawiam to "jak najmniej Dockera", czyli skupiam się na tym, aby wiedza potrzebna do jego wykorzystania nie przysłoniła tej wiedzy, którą chcemy posiąść. 

== Docker i ((Visual Studio Code))

#TODO: Opisać rozszerzenie Docker#

Konfiguracja wymaga rozszerzenia "Remote - Containers". 
Więcej na temat konfiguracji Visual Studio Code pod kontenery znajdziesz https://code.visualstudio.com/docs/remote/containers-tutorial[tutaj].

NOTE: Jeszcze więcej informacji na https://code.visualstudio.com/docs/remote/containers[oficjalnej stronie Microsoft].

Visual Studio Code może działać w środowisko skonteneryzowanym (uruchamiać projekt w Dokerze) poprzez dodanie katalogu `.devcontainer` a w nim pliku `devcontainer.json` służącego do konfiguracji samego środowiska VSC oraz `Dockerfile`, który przechowuje informacje na temat naszego obrazu w którym będziemy pracować.
VSC może uzupełnić strukturę plików za ciebie poprzez polecenie `((Remote-Containers)): Add Development Container Configuration Files`.

#TODO: Dodać przykład z node.js#

Warto zauważyć, że gdy na przyklad uruchomimy aplikacje node.js w kontenerze w Visual Studio Code to automatycznie zostanie otwarty ten port i będzie możliwe otwarcie strony w naszej codziennej przeglądarce.

= Dockerfile
== Problem interakcji
#TODO: Uzupełnić#
Więcej informacji znajdziesz w tym poście: https://linuxhint.com/debian_frontend_noninteractive/.

[source,dockerfile]
----
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install «twoje paczki» <1>

RUN export DEBIAN_FRONTEND=noninteractive <2>
RUN apt-get -y install «twoje paczki»
----

<1> W pierwszym przypadku wyłączamy tryb interaktywny tylko dla tej jednej linijki,
<2> W drugim przypadku całkowicie wyłączamy tryb interaktywny dla budowania obrazu.