== Selekcja rodziców i populacja
W każdej następnej generacji dochodzi do selekcji rodziców w celu wyznaczenia potomków, którzy będą stanowili nową generację.
Rozmiar generacji zależy od natury problemu i zazwyczaj mieści się w zakresie od kilkuset do kilku tysięcy osobników.

Wybór rodziców zazwyczaj opiera się o poziom dopasowania do problemu: im lepszy, tym większe prawdopodobieństwo zostania dawcą genów  <<Kumar2010>>. 
#TODO: TBD#

=== Selekcja ruletkowa
indexterm:[Selekcja, Turniejowa]
Selekcja ruletkowa (oraz selekcja turniejowa – nieporuszana w niniejszej pracy) jest jedną z popularniejszych metod selekcji  <<Kumar2010>>. 
#TODO: TBD#

[source,csharp]
.Implementacja selekcji ruletkowej indexterm:[Selekcja, ruletkowa]
----
public class RouletteSelection
{
    private readonly Random _random = new();
    public bool? IsReversed { get; set; } = null;

    public IEnumerable<T> SelectChromosomes<T>(Generation<T> previousGeneration, int requiredNumberOfParents)
        where T : IChromosome
    {
        if (IsReversed == null) <1>
        {
            var min = previousGeneration.Min();
            var max = previousGeneration.Max();
            IsReversed = max.Fitness < min.Fitness;
        }

        var sumOfFitnesse = 0.0;

        foreach (var chrom in previousGeneration)
        {
            if (!chrom.Fitness.HasValue)
                throw new ArgumentException("Chromosome doesn't have fitness calculated!");

            sumOfFitnesse += chrom.Fitness.Value;
        }

        if (IsReversed == true) sumOfFitnesse = 1.0 / sumOfFitnesse;

        var parentThresholds = new List<double>(requiredNumberOfParents);

        for (int i = 0; i < requiredNumberOfParents; ++i)
            parentThresholds.Add(_random.NextDouble() * sumOfFitnesse);

        parentThresholds = parentThresholds.OrderBy(d => d).ToList(); <2>

        var minimumParentThreshold = parentThresholds[0];

        var selectionProgress = 0.0;
        foreach (var chrom in previousGeneration)
        {
            selectionProgress += IsReversed == true ? 1.0 / chrom.Fitness!.Value : chrom.Fitness!.Value; <3>
            if (minimumParentThreshold > selectionProgress) continue;

            parentThresholds.RemoveAt(0); <4>
            yield return chrom;

            if (parentThresholds.Count == 0) yield break;
            minimumParentThreshold = parentThresholds[0];
        }
    }
}
----

<1> Na początku należy sprawdzić, czy czasem chromosom nie ma odwróconego wartościowania (to znaczy, że lepsza odpowiedź to ta o mniejszej wartości).
<2> Następnie losujemy tyle progów ile rodziców potrzeba (domyślnie 2) wyrażonych w procentach.
<3> Na końcu w bierzemy kolejne chromosomy i dodajemy ich wartości do siebie. W momencie, w którym suma przekroczy procentową wartość progu, aktywny chromosom zostaje wybrany na rodzica.
<4> Algorytm jest powtarzany, aż wszystkie progi zostaną przekroczone.
