= Własna implementacja wybranych operatorów algorytmu genetycznego: test rozwiązań problemu komiwojażera, plecakowego oraz znajdowania minimów wybranych funkcji testowych w porównaniu do PSO
Mikołaj Dalecki <mikdal002@utp.edu.pl>; Mateusz Lewandowski <matlew13@utp.edu.pl>; Karol Appel <karapp002@utp.edu.pl>; Przemysław Nadobny <prznad005@utp.edu.pl>; Jacek Suty <jacsut000@utp.edu.pl>
:toc2:
:imagesdir: ./img
:sectnums:
:iconsdir: ./icons
:sectanchors:
:source-highlighter: pygments
:keywords: asciidoc, wstęp
:doctype: book
:toc-title: Spis treści
:caution-caption: Ostrożnie
:important-caption: Ważne
:note-caption: Uwaga
:tip-caption: Podpowiedź
:warning-caption: Ostrzeżenie
:appendix-caption: Załącznik
:example-caption: Przykład
:figure-caption: Ilustracja
:table-caption: Tabela
:chapter-label: Rozdział
:lang: PL
:hyphens:

[.normal]
Niniejsze sprawozdanie jest rezultatem prac nad algorytmami genetycznymi i ich wykorzystaniem w znajdowaniu rozwiązania problemu komiwojażera/plecakowego i optymalizacji funkcji w porównaniu z algorytmem optymalizacji rojem cząstek (PSO). 
Całość została wykonana przez dwa zespoły:

* Jacek Suty, Przemysław Nadobny i Karol Appel.
* Mikołaj Dalecki i Mateusz Lewandowski,

Zespół pierwszy wykonał i przeanalizował problem plecakowy oraz znalezienia minimum funkcji McCormick'a. 
Do tego odpowiadał za implementację selekcji ruletkowej, krzyżowanie jednorodne (z ang. _uniform selection_), mutację przestawną, mutację losowego resetu i zakończenie pracy algorytmu na podstawie globalnego limitu generacji.
Zespół drugi wykonał i przeanalizował problem komiwojażera, znalezienia minimum funkcji Schwefela i odpowiadał za implementacje pozostałych elementów. 
Fakt odpowiadania za implementację pewnego elementu nie zmienia faktu, że nad całością czuwały oba zespoły i z racji potrzeb oba zespoły nanosiły poprawki i ulepszenia.

include::Wstep/index.adoc[]

include::problemy_i_implementacja/index.adoc[]

== Wnioski
Praca nad implementacją algorytmu genetycznegeo jest niezwykle pouczająca. 


#TODO: TBD# 

[bibliography]
= Bibliografia

* [[[Kumar2010]]] Kumar, Manoj, Mohamed Husain, Naveen Upreti, i Deepti Gupta. 2010. „Genetic Algorithm: Review and Application”. SSRN Electronic Journal. https://doi.org/10.2139/ssrn.3529843.
* [[FalcoCioppa2002]] De Falco, I, A Della Cioppa, i E Tarantino. 2002. „Mutation-Based Genetic Algorithm: Performance Evaluation”. Applied Soft Computing 1 (4): 285–99. https://doi.org/10.1016/S1568-4946(02)00021-2.
* [[wiatrak2015]] Wiatrak, Mateusz, i Ewa Figielska. 2015. „Zastosowanie algorytmu optymalizacji rojem cząstek do znajdowania ekstremów globalnych wybranych funkcji testowych”. Zeszyty Naukowe WWSI 9 (13): 7–19.

[index]
= Indeks