---
draft: true
---
= Podstawy AsciiDoc
Mikołaj Dalecki <mikolaj.dalecki@outlook.com>
v0.1, 2021-05-08: Work in progress
:toc:
:imagesdir: ./img
:sectnums:
:iconsdir: ./icons
:sectanchors:
:source-highlighter: pygments
:keywords: asciidoc, wstęp

[.lead]
Przedstawiam podstawowe komendy i użycia AsciiDoc'a, które są mi niezbędne w trakcie pracy nad blogiem.

[abstract]
== Abstract
 
Tutaj, gdyby artykuł był dłuższy, wpisałbym skrót do całego artykułu.

== Instalacja i konifguracja
=== Visual Studio Code

Aby nie musieć bawić się w konfigurację najlepiej zacząć od obrazu https://hub.docker.com/r/asciidoctor/docker-asciidoctor/[((docker))'a], który zawiera już gotową instalację AsciiDoc (jak korzystać z tego wygodnie w Visual Studio polecam artykuł: #TODO: Wpisać odnośnik#).
W Visual studio należy zmienić ustawienia w następujący sposób:

[source,json,linenums]
.Konfiguracja rozszerzenia AsciiDoctor dla ((Visual Studio Code))
----
{
    "asciidoc.asciidoctor_command": "asciidoctor -r asciidoctor-diagram",
    "asciidoc.asciidoctorpdf_command": "asciidoctor-pdf -r asciidoctor-diagram"
}
----

Oczywiście przypuszczam, że będziesz używać najnowszego rozszerzenia AsciiDoc autorstwa AsciiDoctor'a na moment pisania tego artykułu (2.8.9). 


== Krótki poradnik

Aby zaznaczyć, że jest coś do zrobienia użyj podkreślenia: `#TODO: do zrobienia#` (nawet teraz wyświetla się na żółto).
Dodatkowo warto używać *pogrubienia*, _pochylenia_, `kodu`.

== Różne bloki

NOTE: Pamiętaj, 

[horizontal] 
.Lista słownikowa
property 1:: does stuff
property 2:: does different stuff

[example]
.Opis przykładu
====
To jest przykład
====

[quote, Ja Mikołaj, W Moim Blogu]
.Opis cytatu
____
Cytacik, trochę krótszy, trochę dłuższy, ale jednak jest.
____

[verse]
.Opis czegoś napisanego stylem maszynowym
____
Blok typu verse.
____

[source,csharp]
.Opis kodu źródłowego
----
class PrzykładCSharp <1>
{

}
----
indexterm:[C#, Class]

[sidebar]
.Opis paska Bocznego
****
Pasek boczny, który, co ciekawe, bierze cały rozmiar dla siebie :D.
****

== Diagramy

#TODO: Uzupełnić# 

[ditaa, przykład-ditaa]
.Diagram Ditta
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ Asciidoctor +--> |               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....

[plantuml, przykład-plantuml, png]
.Diagram PlantUML
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....

[plantuml, bezpieczne-warstwy-iot, png]
....
agent Urządzenie
agent Komunikacja
agent Chmura
agent "Cykl życia" as Cykl_Życia

Urządzenie -> Komunikacja
Komunikacja -> Chmura
Chmura -> Cykl_Życia
Cykl_Życia -> Urządzenie
....

[glossary]
== Słownik
Tutaj jest przykład użycia słownika.

[glossary]
mud:: wet, cold dirt
rain::
	water falling from the sky

[index]
== Index

== Na przyszłość

Bibliografia:: https://docs.asciidoctor.org/asciidoc/latest/sections/bibliography/