= Biblioteki .Net którym chcę się przyjrzeć
Mikołaj Dalecki <mikolaj.dalecki@outlook.com>
:toc:

[.lead]
W niniejszym artykule przedstawię biblioteki .Net, nad którymi chciałbym posiedzieć i zgłębić ich tajniki. 
Wypisuję je tutaj, aby o nich nie zapomnieć i dla możliwej dyskusji, na temat tego, którą powinienem zająć się w następnej kolejności. 

== ((FsCheck)) for .Net

https://aaronstannard.com/fscheck-property-testing-csharp-part1/

Pod linkiem podanym wyżej możecie zapoznać się również z krótkim wprowadzeniem do tej funkcji.
Na ogół służy ona do robienia „małpich testów”: podajemy typy wejściowe danych, a biblioteka już sama próbuje wszystkich możliwych kombinacji.
Dodatkową zaletą na pewno jest fakt, że potrafi ona wyświetlić najmniejszy (w domyśle najprostszy) zestaw, który spowodował błąd.

== ((SonnarLint))
SonnarLint'a już zacząłem nawet używać gdzieniegdzie w projekcie, choć jeszcze bez wyraźnego celu. 
Służy on do szukania wszelkiego typu naruszeń w naszym kodzie – przeprowadza statyczną analizę i zaznacza wszystkie znane mu podatności. 
Ogólnie uważam tego typu programy za bardzo przydatne – i choć na początku mogą wydawać się wyjątkowo złośliwe, podkreślając do drugą linijkę w projekcie, to ostatecznie okazuje się, że potrafią wybronić nas przed wieloma głupimi błędami. 