= Trochę o CMake
Mikołaj Dalecki <mikolaj.dalecki@outlook.com>
:toc:
:source-highlighter: pygments

[.lead]
W tym artykule chciałbym przedstawić moje doświadczenia z CMake'm, które uważam za wazne. 

== Zanim zaczniesz
Zanim zaczniesz czytać niniejszy artykuł szukając odpowiedzi na pytania, które w twojej opinii powinny być proste zapoznaj się proszę z dedykowanym https://cmake.org/cmake/help/latest/guide/tutorial/index.html[tutorialem].
Sam przez wiele dni mojej walki z CMake nie miałem o nim pojęcia, a jego odnalezienie (i zapoznanie się!) wprowadziło dużo ładu do mojej pracy – aż wstyd się przyznawać, że nie znalazłem tego na samym początku.

== Chwyty i sztuczki
=== Budowanie równoległe
Do dziś nie rozumiem dlaczego programy budujące same nie wykrywają faktu działania na procesorze wielowątkowym i automatycznie nie wykorzystyują jego całego potencjału. 
Cóż, aby pomóc CMake w podjęciu tej decyzji warto dodać do linii budującej parametr `--parallel 12`. 
Czyli przykładowa linijka budująca domyślnie składana przez QtCreator to: 

#TODO: Sprawdzić, czy nie ma opcji automatycznego doboru liczby wątków#

[source,shell]
.Budowanie projektu z wykorzysatniem wielu wątków maszyny budującej
----
> cmake --build . --target all --parallel 12
----

=== Prostrze zarządzanie definicjami w kodzie (#DEFINE)
Aby nie musiec specjalnie definiować wartości prekompilatora można rozważyć użycie w pliku konfiguracyjnym poleceniea `#cmakedefine NAZWA`. 

#TODO: Podać przykład jak nie ładnie konfigurowałem kod za pomocą prekompilatora.#
#TODO: Sprawdzić, czy #cmakedefine działa również w miejscach po za plikiem .in.#

== Dodawanie podprojektów
W trakcie normalnej pracy z językiem takim jak C# praktycznie zawsze dzielę rozwiązanie na projekt „Core" zawierający możliwie uniwersalne rzeczy dające się łatwo testować oraz projekt "Web" lub "Gui" jako reprezentantów właściwych projektów końcowych. 
W tym rozdziale chciałbym przybliżyć wykorzystywany przeze mnie sposób do takiego rozdziału aplikacji.
