= O .net i C#
Mikołaj Dalecki <mikolaj.dalecki@outlook.com>
:toc:
:source-highlighter: pygments

== Optymalizacja

* W artykule https://leveluppp.ghost.io/loop-optimizations-in-various-compilers/ ciekawie wytłumaczono działanie kompilatora .Net 5.0 w celu optymalizacji pętli.

indexterm:[C#, wskaźniki]
indexterm:[wskaźniki, C#]

* W filmiku https://www.youtube.com/watch?v=Tb2Fx9qku_o przedstawiono niezwykle skuteczne optymalizacje funkcji, gdzie uproszczono operację modulo, usunięto rozgałęzienie (instrukcję if), rozwinięto pętle a nastepnie nawet wykorzystano wskaźniki.

== Biblioteki .Net
Mikołaj Dalecki <mikolaj.dalecki@outlook.com>
:toc:

W niniejszym rozdziale przedstawię biblioteki .Net, nad którymi chciałbym posiedzieć i zgłębić ich tajniki. 
Wypisuję je tutaj, aby o nich nie zapomnieć i dla możliwej dyskusji, na temat tego, którą powinienem zająć się w następnej kolejności. 

=== ConsoleTable

Jak nazwa wskazuje biblioteka ta służy do generowania tekstowych tabel w wersji: klasycznej, minimalistycznej i markdown. 
Biblioteka dostępna pod adresem https://github.com/khalidabuhakmeh/ConsoleTables jest mała i bardzo prosta w użyciu. 
Właściwie składa się z jednego pliku, który odpowiada za formatowanie wyjścia. 
Poniżej kawałek kodu prosto z dokumentacji:

.Przykład użycia ConsoleTable z dokumentacji wraz z moim dodatkiem
[source,csharp]
----
var table = new ConsoleTable("one", "two", "three");
table.AddRow(1, 2, 3)
        .AddRow("this line should be longer", "yes it is", "oh");

table.Write(); <1>
// lub
Console.WriteLine(table.ToMinimalString()); <2>

var rows = Enumerable.Repeat(new Something(), 10);

ConsoleTable
    .From<Something>(rows)
    .Configure(o => o.NumberAlignment = Alignment.Right)
    .Write(Format.Alternative); <1>
----

<1> Użycie metody `Write` dokona wypisania całej tabeli do konsoli. 
Co w przypadku wielu aplikacji może być kompletnie bezsensu. 
Dlatego polecam korzystać z 
<2> `table.toMinimalString()` bądź podobnych.
Zwracają one tabele w postaci stringa i można już wysłać ją gdziekolwiek chcemy.

=== ((FsCheck)) for .Net

https://aaronstannard.com/fscheck-property-testing-csharp-part1/

Pod linkiem podanym wyżej możecie zapoznać się również z krótkim wprowadzeniem do tej funkcji.
Na ogół służy ona do robienia „małpich testów”: podajemy typy wejściowe danych, a biblioteka już sama próbuje wszystkich możliwych kombinacji.
Dodatkową zaletą na pewno jest fakt, że potrafi ona wyświetlić najmniejszy (w domyśle najprostszy) zestaw, który spowodował błąd.

== ((SonnarLint))
SonnarLint'a już zacząłem nawet używać gdzieniegdzie w projekcie, choć jeszcze bez wyraźnego celu. 
Służy on do szukania wszelkiego typu naruszeń w naszym kodzie – przeprowadza statyczną analizę i zaznacza wszystkie znane mu podatności. 
Ogólnie uważam tego typu programy za bardzo przydatne – i choć na początku mogą wydawać się wyjątkowo złośliwe, podkreślając do drugą linijkę w projekcie, to ostatecznie okazuje się, że potrafią wybronić nas przed wieloma głupimi błędami. 