= O powstawianiu bloga
Mikołaj Dalecki <dalecki.mikolaj@gmail.com>
:source-highlighter: pygments
:imagesdir: ./img

== Inspiracje
W moim odczuciu blog mógłby w dużej mierze wyglądać (w kwestii przedstawienia treści) podobnie do strony https://refactoring.guru/pl[Refactoring Guru].

== Luźne notatki
- Wszystkie artykuły będą rozrastać się bądź ewoluować w inny sposób, w długie serie, jak ta o Sztucznej inteligencji.
- Chciałbym mieć możliwość stworzenia strony z bibliografią z całego bloga, gdzie mógłbym również zarządzać linkami afiliacyjnymi do kupna np. książek.
- Chciałbym móc robić możliwie łatwo referencje do innych artykułów w taki sposób, aby były one odporne na przenoszenie plików i pojedynczych sekcji. 
Dodatkowo należy zwrócić uwagę, że w przypadku przenoszenia całych książartów (książka + artykuł) do osobnych repozytoriów potrzebuję dość solidnego mechanizmu odnośników.
- Chcę, aby pierwsze uruchomienie bloga odbyło się jeszcze w 2021 roku.
Inaczej obawiam się, że niektóre rzeczy zdążą się srogo zdezaktualizować.
- Przy tłumaczeniu można by próbować używac np. api deepl'a (https://www.deepl.com/pro#developer).

== Implementacja
* [ ] Chciałbym, aby kod był zaciągany możliwie automatycznie z repozytorium, aby zmniejszyć ilość zmian nanoszonych ręcznie przy publikacji.
+
Pytanie o organizację tego: każdy artykuł może w takim razie mieć własne repozytorium z kodem źródłowym – byłoby to wskazane zwłaszcza przy dużych seriach (patrz artykuł o sztucznej inteligencji).
Dzięki takiemu podejściu łatwiej byłoby utrzymać ten sam stan w artykule i w kodzie. 

* [ ] Automatyczny podział artykułów na rozdziały / sekcje / podsekcje. 
Wybór mógłby być podejmowany w nagłówku artykułu bądź na podstawie ilości tekstu w rozdziale/sekcji/podsekcji.

* [ ] Jak zachować ciągłość komentarzy przy rozwoju z jednego artykułu do wielu?
* [ ] Jak pogodzić artykuły generowane statycznie z takimi, które chciałbym pisać jednorazowo i to najlepiej z wyprzedzeniem? 
Dla przykładu po zakończeniu prac chciałbym napisać krótki artykuł o tym, co będzie nowego i fajnego w najbliższej aktualizacji treści.

* [ ] Rozeznać się w Hugo https://gohugo.io/, footnote:rozw[Wydaje się to być najciekawszym rozwiązaniem]
+
Prosta wielojęzyczna strona wykonana za pomocą Hugo (https://github.com/chaos-eng/chaos-eng.github.io/).

* [ ] Rozeznać się w Wordpress,
* [ ] Rozenznać się w ghost https://ghost.org/
* [ ] Rozeznać się w Netlify https://www.netlifycms.org/, footnote:rozw[]
* [ ] Rozeznać się w Gatsby https://www.gatsbyjs.com/,
* [ ] Zapoznać się z innymi generatorami stron: https://jamstack.org/generators/.

* [ ] Ogarnąć AsciiDoctor Bibliography,
* [ ] Zapoznać się z możliwościami DocBook'a, gdzie AsciiDoctor mógłby odgrywać rolę frontendu (sposobu edycji) dla tego formatu, a ten następnie byłby konwertowany do innych, jak LaTeX czy HTML.
Jego zaletą jest również to, że jest on bardzo dobrze u strukturyzowany, co pozwoli mi łatwo wyciągnąć z niego informacje.

== Proponowany przepływ pracy


[plantuml,przeplyw-artykulow,png]
.Przepływ treści
....
class "Dokument AsciiDoc" as DokumentZrodlowy
class "DockBook pl-PL" as DockBookSource
class "DockBook en-US" as DockBookEN
class "DockBook de-DE" as DockBookDE
class "Artykuł pl-PL" as ArticlePL
class "Artykuł en-DE" as ArticleEN
class "Artykuł de-DE" as ArticleDE

DokumentZrodlowy --|> DockBookSource
DockBookSource --|> DockBookEN
DockBookSource --|> DockBookDE
DockBookSource --|> ArticlePL
DockBookEN --|> ArticleEN
DockBookDE --|> ArticleDE
....

. Z dokumentu AsciiDoc w języku polskim generowany jest DockBook, gdzie każdy element ma swoją sumę kontrolną (np. CRC), co pozwala sprawdzać, czy doszło do zmian.
. Na podstawie polskiego DockBook'a dokonuje się tłumaczenia na obce języki. 
Każdy element zawiera sumę kontrolną elementu, z którego pochodzi w celu potwierdzenia źródła.
. Z każdego DockBooka jest generowany jeden lub wiele artykułów w postaci HTML. 
W przypadku użycia takiego przepływu należy rozważyć dodanie atrybutu "IsPublishReady" aby ominąć publikację niektórych elementów.

[listing]
----
Polski
https://abywnerwicsietylkoraz.pl/pl-PL/1E2E121E12/tytuł-artykułu
Angielski
https://abywnerwicsietylkoraz.pl/en-US/1E2E121E12/article-tytle
https://togetnervousonlyonce.com/1E2E121E12/article-tytle
----

== Podsumowanie plaform
* [ ] Zobaczyc czy jest coś użytecznego tutaj: https://linuxhint.com/open-source-static-site-generators/

.Porównanie funkcjonalności platform
|===
| Platforma | Wielojęzyczność | Testowe uruchomienie | Komentarze | Notatki
| Ghost     | https://ghost.org/docs/tutorials/multi-language-content/[[ X \]]        | Docker | Disqus | REST Api, https://ghost.org/integrations/[Duzo pluginów] (w tym: Google Analitics, Buffer - automatyczna publikacja w Mediach Społecznościowych (MS), GitHub Gists, Transistor – dodawanie podcastów, Feedly)
| Hugo      | [X] TAK        | Docker ?? | Disqus ?? | 
|===

Ghost:: Po krótkiej zabawie widzę, że jest to ciekawe, całkiem dojrzałe narzędzie. 
Zorientowane jest ono na dostarczanie darmowych i płatnych treści (niestety jeszcze nie wypróbowałem jak działają te płate). 
Zasada działania jest podobna do WordPress'a, także ciężko może być mi stworzyć zautomatyzowany system do publikacji.
W przypadku hostowania wymaga on Node.js.

== Wady i zalety języka znaczników AsciiDoctor'a, (rozwiązania, które na ten moment stosuję przy pisaniu):

- nie działa matma :(. 
Nie wiem na ten moment jak używać makra `latexmath`. 
Moim celem jest osiągnięcie renderowania się równań zarówno w druku, jak i w przeglądarce – na ten moment nie udało mi się tego osiągnąć.
- Brak wykresów prosto z kodu. 
Brakuje mi funkcjonalności pozwalającej na generowanie wykresów w ten sam sposób, jak generowane są diagramy.
Niby to (https://github.com/asciidoctor/asciidoctor-chart), ale jednak nie udało mi się tego uruchomić.
- W konstrukcji drzewiastej katalogów (kiedy każdy rozdział lub tom znajdują się w innym folderze) obrazki dalej muszą być przechowywane w lokalizacji względem katalogu głównego. 

Problemy przy generowaniu PDF'a:

- kompletny brak kontroli wdów i innych błędów typograficznych, np. opis zdjęcia/tabeli/kodu potrafi być na innej stronie niż na tej, co obraz.
- brak płynnej kontroli elementów: obrazy pojawiają się DOKŁADNIE tam, gdzie wprowadzisz je w kodzie.
W LaTeX'u są one płynne.

= Pomysły na artykuły i serie

= Inne blogi i strony warte uwagi

- https://cezarywalenciuk.pl/ - aktywnie rozwijany blog o technologiach .Net oraz przemówieniach.
Znajdziesz na nim rzeczy stricte o kodzie (nowe technologie, biblioteki, itp.) jak i bardziej abstrakcyjne jak architektura czy wzorce projektowe.
- https://crossweb.pl/podcasty/ – lista podcastów o technologiach, IT i programowaniu.
- https://leveluppp.ghost.io/ - blog o technologiach .Net (i nie tylko) na którym znalazłem ciekawe niskopoziomowe (o IL) wpisy.

== Ciekawe blogi ale nie tak bardz

- https://programistanaswoim.pl/ - blog który w swojej historii miał na celu przedstawienie jak przejść na własną działalność jako programista.
Niestety nie jest on już za często aktualizowany.
- https://www.meziantou.net/ - całkiem bogaty w treści blog prowadzony przez MVP Microsoftu. Blog traktuje o technologiach .Net itp.
