= O powstawianiu bloga
Mikołaj Dalecki <dalecki.mikolaj@gmail.com>

== Inspiracje
W moim odczuciu blog mógłby w dużej mierze wyglądać (w kwestii przedstawienia treści) podobnie do strony https://refactoring.guru/pl[Refactoring Guru].

== Luźne notatki
- Wszystkie artykuły będą rozrastać się bądź ewoluować w inny sposób, w długie serie, jak ta o Sztucznej inteligencji.
- Chciałbym mieć możliwość stworzenia strony z bibliografią z całego bloga, gdzie mógłbym również zarządzać linkami afiliacyjnymi do kupna np. książek.
- Chciałbym móc robić możliwie łatwo referencje do innych artykułów w taki sposób, aby były one odporne na przenoszenie plików i pojedynczych sekcji. 
Dodatkowo należy zwrócić uwagę, że w przypadku przenoszenia całych książartów (książka + artykuł) do osobnych repozytoriów potrzebuję dość solidnego mechanizmu odnośników.
- Chcę, aby pierwsze uruchomienie bloga odbyło się jeszcze w 2021 roku.
Inaczej obawiam się, że niektóre rzeczy zdążą się srogo zdezaktualizować.

== Implementacja
* [ ] Chciałbym, aby kod był zaciągany możliwie automatycznie z repozytorium, aby zmniejszyć ilość zmian nanoszonych ręcznie przy publikacji.
+
Pytanie o organizację tego: każdy artykuł może w takim razie mieć własne repozytorium z kodem źródłowym – byłoby to wskazane zwłaszcza przy dużych seriach (patrz artykuł o sztucznej inteligencji).
Dzięki takiemu podejściu łatwiej byłoby utrzymać ten sam stan w artykule i w kodzie. 

* [ ] Automatyczny podział artykułów na rozdziały / sekcje / podsekcje. 
Wybór mógłby być podejmowany w nagłówku artykułu bądź na podstawie ilości tekstu w rozdziale/sekcji/podsekcji.

* [ ] Jak zachować ciągłość komentarzy przy rozwoju z jednego artykułu do wielu?
* [ ] Jak pogodzić artykuły generowane statycznie z takimi, które chciałbym pisać jednorazowo i to najlepiej z wyprzedzeniem? 
Dla przykładu po zakończeniu prac chciałbym napisać krótki artykuł o tym, co będzie nowego i fajnego w najbliższej aktualizacji treści.

* [ ] Rozeznać się w Hugo https://gohugo.io/, footnote:rozw[Wydaje się to być najciekawszym rozwiązaniem]
* [ ] Rozeznać się w Wordpress,
* [ ] Rozeznać się w Netlify https://www.netlifycms.org/, footnote:rozw[]
* [ ] Rozeznać się w Gatsby https://www.gatsbyjs.com/,
* [ ] Zapoznać się z innymi generatorami stron: https://jamstack.org/generators/

* [ ] Ogarnąć AsciiDoctor Bibliography
* [ ] Zapoznać się z możliwościami DocBook'a, gdzie AsciiDoctor mógłby pełnić rolę frontendu (sposobu edycji) dla tego formatu, a ten następnie byłby konwertowany do innych, jak LaTeX czy HTML.
Jego zaletą jest również to, że jest on bardzo dobrze ustrukturyzowany, co pozwoli mi łatwo wyciągnąć z niego informacje
== Wady i zalety języka znaczników AsciiDoctor'a, (rozwiązania, które na ten moment stosuję przy pisaniu):

- nie działa matma :(. 
Nie wiem na ten moment jak używać makra `latexmath`. 
Moim celem jest osiągnięcie renderowania się równań zarówno w druku jak i w przeglądarce – na ten moment nie udało mi się tego osiągnąć.
- Brak wykresów prosto z kodu. 
Brakuje mi funkcjonalności pozwalającej na generowanie wykresów w ten sam sposób, jak generowane są diagramy.
Niby to (https://github.com/asciidoctor/asciidoctor-chart), ale jednak nie udało mi się tego uruchomić.
- W konstrukcji drzewiastej katalogów (kiedy każdy rozdział lub tom znajdują się w innym folderze) obrazki dalej muszą być przechowywane w lokalizacji względem katalogu głównego. 