= O powstawianiu bloga
Mikołaj Dalecki <dalecki.mikolaj@gmail.com>

== Inspiracje
W moim odczuciu blog mógłby w dużej mierze wyglądać (w kwestii przedstawienia treści) podobnie do strony https://refactoring.guru/pl[Refactoring Guru].

== Luźne notatki
- Wszystkie artykuły będą rozrastać się bądź ewoluować w inny sposób, w długie serie, jak ta o Sztucznej inteligencji.
- Chciałbym mieć możliwość stworzenia strony z bibliografią z całego bloga, gdzie mógłbym również zarządzać linkami afiliacyjnymi do kupna np. książek.
- Chciałbym móc robić możliwie łatwo referencje do innych artykułów w taki sposób, aby były one odporne na przenoszenie plików i pojedynczych sekcji.

== Implementacja
* [ ] Chciałbym, aby kod był zaciągany możliwie automatycznie z repozytorium, aby zmniejszyć ilość zmian nanoszonych ręcznie.
+
Pytanie o organizację tego: każdy artykuł może w takim razie mieć własne repozytorium z kodem źródłowym – byłoby to wskazane zwłaszcza przy dużych seriach (patrz artykuł o sztucznej inteligencji).
Dzięki takiemu podejściu łatwiej byłoby utrzymać ten sam stan w artykule i w kodzie. 

* [ ] Automatyczny podział artykułów na rozdziały / sekcje / podsekcje. 
Wybór mógłby być podejmowany w nagłówku artykułu.

* [ ] Jak zachować ciągłość komentarzy przy rozwoju z jednego artykułu do wielu?
* [ ] Jak pogodzić artykuły generowane statycznie z takimi, które chciałbym pisać jednorazowo i to najlepiej z wyprzedzeniem? 
Dla przykładu po zakończeniu prac chciałbym napisać krótki artykuł o tym, co będzie nowego i fajnego w najbliższej aktualizacji treści.

* [ ] Rozeznac się w Hugo https://gohugo.io/, footnote:rozw[Wydaje się to być najciekawszym rozwiązaniem]
* [ ] Rozeznać się w Wordpress,
* [ ] Rozeznać się w Netlify https://www.netlifycms.org/, footnote:rozw[]
* [ ] Rozeznać się w Gatsby https://www.gatsbyjs.com/,
* [ ] Zapoznać się z innymi generatorami stron: https://jamstack.org/generators/

== Wady i zalety języka znaczników AsciiDoctor'a, (rozwiązania, które na ten moment stosuję przy pisaniu):

- nie działa matma :(. 
Nie wiem na ten moment jak używać makra `latexmath`. 
Moim celem jest osiągnięcie renderowania się równań zarówno w druku jak i w przeglądarce – na ten moment nie udało mi się tego osiągnąć.
- Brak wykresów prosto z kodu. 
Brakuje mi funkcjonalności pozwalającej na generowanie wykresów w ten sam sposób, jak generowane są diagramy.
- W konstrukcji drzewiastej katalogów (kiedy każdy rozdział lub tom znajdują się w innym folderze) obrazki dalej muszą być przechowywane w lokalizacji względem katalogu głównego. 