---
title: Polityka prywatności
date: '2021-07-31'
aliases:
  - rodo
  - privacy-policy
  - gpdr
lastmod: '2021-07-05'
menu:
    main: 
        weight: -0
        pre: privacy
---

== REKLAMY 
Na tym blogu używam reklam firm trzecich (takich jak Google AdSense), aby go wspierać. 
Niektórzy z tych reklamodawców mogą używać plików cookie do wyświetlania reklam na podstawie wcześniejszych wizyty użytkownika na tej stronie lub innych stronach internetowych.

== GOOGLE ANALYTICS
Na tej stronie korzystam z Google Analytics . 
Używa one plików cookie, aby pomóc witrynie analizować, co użytkownicy czytają i przeglądają.

Informacje generowane przez cookie na temat korzystania z witryny przez użytkownika (w tym jego adres IP) są przekazywane firmie Google i przechowywane na jej serwerach. 
Google będzie korzystała z tych informacji w celu oceny korzystania z witryny przez użytkownika, tworzenia raportów dotyczących ruchu na stronach dla operatorów witryn oraz świadczenia innych usług związanych z ruchem na witrynach internetowych i korzystaniem z internetu. 
Google może również przekazywać te informacje osobom trzecim, jeżeli będzie zobowiązana to uczynić na podstawie przepisów prawa lub w przypadku, gdy osoby te przetwarzają takie informacje w imieniu Google. 
Google nie będzie łączyć adresu IP użytkownika z żadnymi innymi danymi przechowywanymi przez Google.

Użytkownik może zrezygnować z cookies, wybierając odpowiednie ustawienia w swojej przeglądarce, w https://www.google.com/settings/ads[ustwieniach reklam  Google] lub też poprzez odpowiednią konfigurację na stronie http://www.aboutads.info/choices/.

Aby dowiedzieć się więcej, zobacz policies.google.com/technologies/partner-sites.

== Podsumowanie

Możesz kontrolować sposób, w jaki wykorzystujemy Twoje dane, klikając przycisk "Ustawienia prywatności i plików cookie" znajdujący się na dole tej witryny.

Przetłumaczono z www.DeepL.com/Translator (wersja darmowa)

[.small]
Ikona tej pozycji menu została wykonana przez https://freeicons.io/profile/135331[Chanut is Industries] https://freeicons.io/[freeicons.io]