---
title: Privacy policy
date: '2021-07-31'
aliases:
  - rodo
  - privacy-policy
  - gpdr
lastmod: '2021-07-05'
menu:
    main: 
        weight: -0
        pre: privacy
---

== ADVERTISEMENTS 
I use third party advertisements (like Google AdSense) on this blog to support it. 
Some of these advertisers may use cookies to serve ads based on a user's prior visits to our website or other websites.

== GOOGLE ANALYTICS
I use Google Analytics on this site. 
It uses cookies to help the website analyse what users read and browse for.

The information generated by the cookie about your use of the websites (including your IP address) will be transmitted to and stored by Google on their servers. 
Google will use this information for the purpose of evaluating your use of the websites, compiling reports on website activity for website operators, and providing other services relating to website activity and internet usage. 
Google may also transfer this information to third parties when required to do so by law, or where such third parties process the information on Google's behalf. 
Google will not associate your IP address with any other data held by Google.

You may refuse the use of cookies by selecting the appropriate settings on your browser, at https://www.google.com/settings/ads[Google Ads Settings] or by configuring the appropriate settings on http://www.aboutads.info/choices/.

To find out more, see policies.google.com/technologies/partner-sites.

== Summary

You can control how we use your data by clicking button on the bottom of this site called "Privacy and cookie settings".

Icon of this menu position was made by https://freeicons.io/profile/135331[Chanut is Industries] https://freeicons.io/[freeicons.io]